export const mockStoreState = {
  loading: true,
  error: false,
  usersData: [],
  billsData: [],
  hasBillPreviewData: false,
  billPreviewData: [],
  hasBillEditData: false,
  billEditData: [],
  billInEditMode: false,
  costTypes:['Food', 'Entertainment', 'Health and Beauty', 'Other'],
  showLogoutWindow: false,
  showAddBillForm: false,
  addBillFormData: {},
  userData:{first_name: '', last_name: '', email:''},
  hasAccountData: false,
  accountData: [],
  accountHasBillEditData: false,
  accountBillEditData: {},
  hasExchangeRates: false,
  exchangeRates: {},
};