# Generated by Django 4.0.4 on 2022-10-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Russian rubble'), ('USD', 'US dollar'), ('EUR', 'Euro'), ('KZT', 'Kazakhstani tenge')], default='RUB', max_length=3),
        ),
    ]
